name: SQL Schema Linter

# Дозволяє запускати цей воркфлоу вручну з вкладки Actions
on: workflow_dispatch

jobs:
  sql-linter-check:
    name: Run SQLFluff Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Start SQL Linter
        run: |
          pip install sqlfluff
          
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect postgres
