name: JavaScript Code Linter (Biome)

# Дозволяє запускати вручну для експериментів
on: workflow_dispatch

jobs:
  JavaScriptCodeLinter:
    name: Run Biome Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Install Biome JS Linter
        run: |
          npm install --save-dev --save-exact @biomejs/biome

      - name: Validate JS file (expected to fail)
        run: |
          npx @biomejs/biome check ./ProgramCodeModified.js
